### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by icattlecoder**

### CODE REVIEW

**Comment by ashchan** [comment]
@xxuejie Was this `tho` initially meant to be `though` or `the`?

**Comment by ashchan** [comment]
@icattlecoder Thanks for this but `tho` means `though` in this context so it's actually not a typo.

**Comment by xxuejie** [comment]
This is indeed meant to be short for `though`.

**Comment by ashchan** [comment]
Updated `tho` to `though` with 3eb4cd5b15fdc495e9976194ad0e5112c0a03504.

**Pull request closed without merging**
