### PR TITLE
test: add rpc test

### PR DESCRIPTION
**Pull request by classicalliu**

### CODE REVIEW

**Comment by doitian** [comment]
Does the test require a running CKB node? If so, I recommend recording web requests using gems like VCR.

**Comment by ashchan** [comment]
@doitian It does need a node.

The Swift SDK is currently skipping RPC test on CI. Recording RPC requests would be a good idea but we're lacking time now. I'd like to see unit tests up and running on CI first.

**Comment by ashchan** [comment]
Oops, isn't the `.travis.yml` file supposed to be under the root folder? @classicalliu

**Comment by classicalliu** [comment]
> [](https://github.com/nervosnetwork/ckb-demo-ruby-sdk/pull/60)

Oh no, maybe some mistake here....

**Comment by classicalliu** [comment]
> Oops, isn't the `.travis.yml` file supposed to be under the root folder? @classicalliu
> 
> #60

Oh no, maybe some mistake here....

**Pull request merged**
